// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOuHNAfnhuNSaXIKdg_oBm4kn-pJVYcwc',
    appId: '1:462916155679:web:703a8946f6e03efa85d82a',
    messagingSenderId: '462916155679',
    projectId: 'jardimsecretofirebase',
    authDomain: 'jardimsecretofirebase.firebaseapp.com',
    storageBucket: 'jardimsecretofirebase.appspot.com',
    measurementId: 'G-M73TR5CJW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc8brmZxJ26tBc0gGDoqEvwry9zrkdeGQ',
    appId: '1:462916155679:android:7ca170ddcc43c72085d82a',
    messagingSenderId: '462916155679',
    projectId: 'jardimsecretofirebase',
    storageBucket: 'jardimsecretofirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiRYXjOcWaQKqPqOcUlasw-TL8vzmSVc8',
    appId: '1:462916155679:ios:6655569f392a1dd585d82a',
    messagingSenderId: '462916155679',
    projectId: 'jardimsecretofirebase',
    storageBucket: 'jardimsecretofirebase.appspot.com',
    iosBundleId: 'com.example.rdCatalogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiRYXjOcWaQKqPqOcUlasw-TL8vzmSVc8',
    appId: '1:462916155679:ios:6655569f392a1dd585d82a',
    messagingSenderId: '462916155679',
    projectId: 'jardimsecretofirebase',
    storageBucket: 'jardimsecretofirebase.appspot.com',
    iosBundleId: 'com.example.rdCatalogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOuHNAfnhuNSaXIKdg_oBm4kn-pJVYcwc',
    appId: '1:462916155679:web:76dfbcd31a928e1b85d82a',
    messagingSenderId: '462916155679',
    projectId: 'jardimsecretofirebase',
    authDomain: 'jardimsecretofirebase.firebaseapp.com',
    storageBucket: 'jardimsecretofirebase.appspot.com',
    measurementId: 'G-FW7RKD6E2P',
  );

}